### ISSUE TITLE
What's the compile time threading modes of the native library?

### ISSUE THREAD

**Issue by qiuxiafei** [xerial/sqlite-jdbc#199]
As the [document](http://www.sqlite.org/threadsafe.html) mention SQLite has 3 thread modes: `Single-thread`, `Multi-thread` and `Serialized`. So what's the compile-time thread mode of sqlite-jdbc and does sqlite-jdbc provide the capability the change it at runtime?

**Comment by xerial** [comment]
sqlite-jdbc is compiled with SQLITE_THREADSAFE=1 (multi-thread mode) https://www.sqlite.org/compile.html#threadsafe
This cannot be changed at runtime.

**Comment by qiuxiafei** [comment]
Thanks, xerial. It would be a good feature if the thread-mode can be changed at runtime.

**Comment by qiuxiafei** [comment]
Hi, xerial. I wonder why doesn't sqlite-jdbc choose SQLITE_THREADSAFE=2 as the default?

**Comment by patcheng** [comment]
The thread model choices were discussed here: 
https://github.com/xerial/sqlite-jdbc/issues/59

Basically, 
SQLITE_THREADSAFE=0 is bad, because it's not thread-safe.
SQLITE_THREADSAFE=1 is the default behavior, and can be modified at runtime (when sqlite-jdbc supports it).
SQLITE_THREADSAFE=2 is bad, because it breaks existing apps.

**Comment by qiuxiafei** [comment]
OK thanks!

**Comment by peoplesbeer** [comment]
> sqlite-jdbc is compiled with SQLITE_THREADSAFE=1 (multi-thread mode) https://www.sqlite.org/compile.html#threadsafe

I believe there's a typo in the above quote, as is stated in the link: `SQLITE_THREADSAFE=1` sets the default threading mode to Serialized (NOT multi-threaded).

**Comment by buko** [comment]
Just to confirm the expected behavior of xerial:

1. Xerial's sqlite is compiled with SQLITE_THREADSAFE=1. This sets the threading mode to Serialized. Multiple threads can access a SQLite database at the same time but each thread must obtain its own JDBC Connection.
2. The threading-model is serialized. This means, I think, that the threads won't actually proceed concurrently. A second thread won't be able to do anything until the first thread closes its Connection. The underlying SQLite db is threadsafe but only offers serialized concurrency level.
3. It is possible to change the sqlite concurrency level at runtime but Xerial does not offer a Java API. At least there's nothing in the SQLiteConfig class that can be used to change this.

Is this correct?
