### ISSUE TITLE
Suggestion: use the sqlite3_auto_extension() function

### ISSUE THREAD

**Issue by kroggen** [xerial/sqlite-jdbc#228]
Hi guys!

What about using the [sqlite3_auto_extension()](https://sqlite.org/c3ref/auto_extension.html) function instead of [modifying](https://github.com/xerial/sqlite-jdbc/blob/e3766561261cecadd5eba9cc13cb23c8e1bf0f52/Makefile#L57-L59) the sqlite3.c file to load the extensions?

Is it possible?

**Comment by gotson** [comment]
I honestly can't assess such a change. Suggest you try and submit a PR if you want.

**Comment by gotson** [comment]
I recently worked on that area of the code, here is my understanding:
- `RegisterExtensionFunctions` is part of [this extension](https://github.com/xerial/sqlite-jdbc/blob/4ba3c9fccbf609917f5351942552992562c54ffb/src/main/ext/extension-functions.c#L1697) as source code
- [during the build](https://github.com/gotson/sqlite-jdbc/blob/master/Makefile#L71-L71), the content of that file is added to `sqlite3.c`
- that's why we need to call `RegisterExtensionFunctions` by modifying the code

It basically adds upon the existing amalgamation, and compiles the whole thing in one go.

If you think the above could help and want to submit a PR, please feel free.
