### ISSUE TITLE
Library creates endless .dll and .lck files in the temp folder

### ISSUE THREAD

**Issue by voidburn** [xerial/sqlite-jdbc#305]
OS: Windows 10 64bit latest updates. 
JDK: version "1.8.0_152"

Looks like #173 is not working anymore?

**Comment by elena321** [comment]
I've facing the same problem with last driver sqlite-jdbc-3.21.0.jar

**Comment by witmoca** [comment]
I'm unable to reproduce the issue on the same OS. 
@elena321 I assume that you are using a Windows system as well.  Please comfirm and check what version of JDK you are using just in case. 

As i can't see the same issue happening, is there any chance that your program get's terminated in an unnatural way (Like being forced to stop, etc...)?
Normally as the JVM exits the .lck gets deleted. Any sqlite-jdbc dll's that don't have corresponding .lck files get deleted the next time a new dll file is created. The .lck file doesn't get deleted however if the JVM doesn't close naturally.

**Comment by voidburn** [comment]
That could very well be the proble during development! Haven't thought
about that!

On Jan 17, 2018 19:30, "Jente Heremans" <notifications@github.com> wrote:

I'm unable to reproduce the issue on the same OS.
@elena321 <https://github.com/elena321> I assume that you are using a
Windows system as well. Please comfirm and check what version of JDK you
are using just in case.

As i can't see the same issue happening, is there any chance that your
program get's terminated in an unnatural way (Like being forced to stop,
etc...)?
Normally as the JVM exits the .lck gets deleted. Any sqlite-jdbc dll's that
don't have corresponding .lck files get deleted the next time a new dll
file is created. The .lck file doesn't get deleted however if the JVM
doesn't close naturally.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xerial/sqlite-jdbc/issues/305#issuecomment-358398290>,
or mute the thread

**Comment by magao** [comment]
I'm assuming that the sqlite-jdbc driver aquires a write lock on the .lck files.

In that case, on startup wouldn't it be possible to attempt to acquire a write lock on each .lck file, and if it's successfully acquired then we know no other process has the corresponding DLL loaded, and both the lock file and DLL can be deleted.

This could significantly increase the startup time in the case that lots of processes were actually using sqlite-jdbc concurrently (and so the lock files were legitimate). So maybe only do this for lock files that are "old", and touch the file occasionally to ensure the modified date is updated. e.g. only do this for lock files that haven't been modified for at least a day, and when using the driver (e.g. executing a command - I'm sure there's a central-enough location in the code), touch the lock file if its last-modified is more than an hour ago (don't need to stat for that - can just keep the last-modified in memory since we have a write lock).

Since the main identified use case is a process terminating abnormally (esp. a developer killing a process, something I do regularly) I think this would keep things under control. Maybe a system parameter to specify how old lock files need to be for the check to be performed.
