### ISSUE TITLE
Proper / secure way to receive last_insert_rowid

### ISSUE THREAD

**Issue by b3nn0** [xerial/sqlite-jdbc#329]
Hi,
right now there are multiple ways to retrieve the last inserted rowid of an insert.
None of them is very good.
- Query for "SELECT last_insertrowid()":
-> Doesn't work in multithreaded applications

- Add the select statement directly behind the INSERT query, e.g.
"INSERT INTO a VALUES('x'); SELECT last_insert_rowid()"
-> Doesn't work when the insert is a prepared statement. SQLite will only respect the first statement.

- Call stmt.getGeneratedKeys()
-> Just as unreliable. It seems to do a lazy call to last_insert_rowid(), which is, in my opinion, a bug.

As SqliteJdbc seems to synchronize everything going to SQLite, it would be quite easy to fix.
To do so, the library simply would need to call sqlite3_last_insert_rowid() right after the query.
JDBC already provides the API, see Statement.RETURN_GENERATED_KEYS constant.

Implementing it should be quite simple...
I could potentially provide a patch, if it has the chance to be accepted.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
I've been thinking about this, and I think option 2 would require to have a sql parser. We would need to be able to find out whether there is already a RETURNING clause, and also to find out what's the table name so that we can infer the generated keys too.

**Comment by gotson** [comment]
@b3nn0 in the next major version the driver will not support anymore `getGeneratedKeys`, as there is no reliable way to retrieve those. The good way would be to use the SQLite `RETURNING` clause.

**Comment by b3nn0** [comment]
Alright, makes sense. Closing this then.

**Comment by sproket** [comment]
How is removing a feature resolved? Anyway it breaks Persism but I'm doing it the new way for SQLite and it's working so I'll put out an update soon.

**Comment by barrycaceres** [comment]
If I am reading this correctly, the ability to obtain the generated keys has been removed entirely with no "proper" way to do it?

Those of us who were managing our connections and atomically doing single inserts and then immediately obtaining the generated keys were having no problem with the existing functionality because we understood that using it meant doing a single insert and before letting any other thread get your `Connection` object you had to get the generated key.

Simply removing this functionality because it did not work for those who did not understand how to do it safely seems like a non-fix but like crippling access to SQLite via JDBC.

**Comment by barrycaceres** [comment]
> How is removing a feature resolved? Anyway it breaks Persism but I'm doing it the new way for SQLite and it's working so I'll put out an update soon.

BINGO!  You are so right.  Somebody dropped the ball here.
