### ISSUE TITLE
How to programmatically configure for MultiThread?

### ISSUE THREAD

**Issue by pixelpshr** [xerial/sqlite-jdbc#348]
I can get threadsafe execution by using the command line argument "SQLITE_THREADSAFE=2", but I'd like to change the configuration programmatically to avoid the command line argument. I found the SQLiteConfig class, but it doesn't seem to have any setter for THREADSAFE. Can anyone tell me how to set this within my java code?

thanks,
Thom

**Comment by witmoca** [comment]
I don't believe that's possible.  You could compile with `SQLITE_THREADSAFE=2` so its permanently set to 2, but sqlite-jdbc can't change that setting at runtime currently. 

According to the sqlite3 docs: [sqlite3 threadsafe doc](https://sqlite.org/threadsafe.html) you have to use `sqlite3_open_v2()`. We use `sqlite3_open()` instead of the v2, so threadsafe defaults to the compile time setting.

**Comment by gotson** [comment]
Closing as duplicate of #369
