### ISSUE TITLE
SQLite only supports TYPE_FORWARD_ONLY cursors

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [xerial/sqlite-jdbc#379]
I have the error `SQLite only supports TYPE_FORWARD_ONLY cursors` when using `sqlite-jdbc-3.23.1` loaded in libreoffice base `6.1.2.1` with oracle JRE `1.8.0_181`
See also https://bitbucket.org/xerial/sqlite-jdbc/issues/120/javasqlsqlexception-sqlite-only-supports

**Comment by calfzhou** [comment]
same issue.... any progress on this?

**Comment by jcbollinger** [comment]
This is not a bug in the driver.  JDBC drivers are permitted to support forward-only ResultSets, in part because that's the only kind that some database engines themselves support.  And SQLite is one such engine.

**Comment by jtphoenixga** [comment]
> This is not a bug in the driver. JDBC drivers are permitted to support only forward-only ResultSets, in part because that's the only kind that some database engines themselves support. And SQLite is one such engine.

If it's not a bug, then what's going on here?  It's odd that the user is able to setup up a JDBC driver connection to assist with data manipulation only to be thrown this error message.  What's the point of allowing a data connection to be created, but not able to view or manipulate the data because the 'cursor' isn't supported.  If this isn't possible, then the data connections shouldn't be allowed.

**Comment by jcbollinger** [comment]
> If it's not a bug, then what's going on here? It's odd that the user is able to setup up a JDBC driver connection to assist with data manipulation only to be thrown this error message.

It's not a bug *in the driver*, but possibly it can be characterized as a bug in Base.  I think that's a bit harsh, though.  It could possibly be characterized as a user error to attempt to use a JDBC driver that does not satisfy Base's minimum requirements.

In any event, Base has requirements of JDBC drivers that this driver does not satisfy (and is within its rights not to satisfy).  It could conceivably check those requirements when the user first sets up a connection, but that does not rule out the possibility that something will change later.  When Base detects a failure, it provides sufficient information to characterize the issue.

> What's the point of allowing a data connection to be created, but not able to view or manipulate the data because the 'cursor' isn't supported. If this isn't possible, then the data connections shouldn't be allowed.

Forward-only result sets -- the kind this driver provides -- are perfectly suitable for many data-manipulation tasks.  For substantially all tasks that SQLite is successfully used for, in fact, because forward-only access is the only mode that SQLite's C-language API and the underlying engine support.  It's not immediately clear to me that Base really requires more, *vs.* it asking for a feature that in practice it could do without.

Personally, I worked around this issue by installing an ODBC driver for SQLite, and setting up ODBC connections to my SQLite databases.  Base uses these successfully.  I am uncertain whether the ODBC driver does some kind of internal magic to provide for scrollability or whether Base just works with forward-only style in this configuration.  I would have preferred JDBC, but that's not a viable option, at least not with this driver, and again, that does not make this driver buggy.

**Comment by gotson** [comment]
See https://github.com/xerial/sqlite-jdbc/issues/682#issuecomment-950687433

This is not possible in SQLite.

**Comment by f1-outsourcing** [comment]
Is it not possible to create an option so it mimics more or less this behaviour and this sqlite can be used with libre office?

jdbc:sqlite:C:/temp/test.db?aaaa=bbbb
