### ISSUE TITLE
Update to 3.26.0 to address "Magellan" vulnerability

### ISSUE THREAD

**Issue by mattsheppard** [xerial/sqlite-jdbc#389]
https://blade.tencent.com/magellan/index_en.html reports a vulnerability in SQLite versions prior to 3.26.0, which they are calling Magellan. They suggest that vulnerable versions of SQLite can be exploited to allow remote code execution.

Any chance we might get the latest version of SQLite packaged up to avoid this (or in my case avoid having to explain why we're actually probably not vulnerable to anyone)?

https://news.ycombinator.com/item?id=18686305 seems to contain a little more detail about what someone thinks the vulnerability is actually about if it's of any interest.

**Comment by ozzi-** [comment]
Statement of  D. Richard Hipp (creator of SQLite) said:
_Reports of an RCE vulnerability in SQLite are greatly exaggerated. Some clever gray-hats found a way to get RCE using maliciously crafted SQL. So, IF you allow random internet users to run arbitrary SQL on your system, you should upgrade. Otherwise, you are not at risk._
Source: https://twitter.com/DRichardHipp/status/1073779742552350720

Further description of the vulnerability (https://nakedsecurity.sophos.com/2018/12/19/sqlite-creator-fires-back-at-tencents-bug-hunters/):
The flaw lies not in the core SQLite engine itself, but in FTS3, a full-text search module that developers can use with the system. Sending SQL commands to FTS3 can trigger the flaw. An attacker might do that by directing an application using SQLite to visit a malicious website, which could then send the SQL commands using JavaScript.

**Comment by Krishnaghimire** [comment]
Are we targeting it in the next release?

**Comment by witmoca** [comment]
Current release is past this issue. Ready for closure

**Comment by mattsheppard** [comment]
Is there a new release? The home page still lists "2018-10-01: sqlite-jdbc-3.25.2" as the latest.

**Comment by witmoca** [comment]
The news just hasn't been updated. Xerial released update 3.72.2 some hours ago. Check releases.

**Comment by xerial** [comment]
Yes. I've just released 3.27.2 yesterday. We can close this.
