### ISSUE TITLE
SQLite JDBC in FreeBSD Ports

### ISSUE THREAD

**Issue by lapo-luchini** [xerial/sqlite-jdbc#495]
Hi, I'm the maintainer of current [sqlitejdbc FreeBSD Port](https://www.freshports.org/java/sqlitejdbc/), based on (ancient) version 056 by Zentus.

That Port (which produces also a binary package on all supported platforms) uses a very small shared library which depends on the system SQLite3 library (which is of course a dependency of that package) and avoid any "pure Java" version, given that that package always provides a native library compatible with the current system; this makes the Port still useful as the used SQLite3 library is always updated (even if the Java wrapper wasn't, in years).

This is a different approach from the one that this project currently has, and I was wondering how I should upgrade that old package using the new codebase here (which adds JDBC4 among other features and fixes). Using the system sqlite3 library is best for security, because that's a very common package (already installed in most systems anyways) and upgrading it independently from the JDBC package ensures it's always updated with latest fixes, but on the other hand, I notice that the `make native` target is `sed`-ing some modifications to SQLite sources, would it even work if modified to link an external (standard) `libsqlite3.so`?

**Comment by michael-o** [comment]
Ciao @lapo-luchini this is somewhat similar to #462 because it needs to be solved first before it can make it properly with zero or minimal changes into the ports tree. I had the same issue on HP-UX and added support for external amalgamation in #466. You basically need to patch the `Makefile` to  provide a `native-shared` target with `SQLITE_SHOBJ` first.

The port should do then the following:
1. Have `libsqlite3.so` available in `LOCALBASE`
2. Fetch source code from GitHub tag, compile with `native-shared` from source and link against the `libsqlite3.so`, no amalgamation.
3. Download the JAR from Maven Central and remove the `native/` directory from the JAR. There is no need to recompile the Java source with Maven, infact it won't work due to the offline requirement during port build.
4. Emit a pkg message on install that the lib path needs to be set until #462 is resolved.

PS: You did not react on my donation request for asn1.js ;-)
