### ISSUE TITLE
Sqlite3.31.1 Security vulnerability resolution plan

### ISSUE THREAD

**Issue by g00229729** [xerial/sqlite-jdbc#503]
SQLite3 3.31.1 has security vulnerabilities, such as CVE-2020-13630, CVE-2020-13434,CVE-2020-13632,CVE-2020-13435. Do you have a detailed plan for fixing the vulnerabilities? What is the version in which the vulnerabilities are expected to be fixed?

**Comment by witmoca** [comment]
You can update to do new version of SQLite JDBC, it's already available.

Version 3.32.3 of this JDBC driver was released specifically for this purpose. Considering these are problems within SQLite and not the JDBC driver, our only course of action was updating to the new SQLite version, as has been done. 
Issue #501 has a more detailed list of relevant CVE's. 

Please note that we are **not**  the developers of SQLite . This project is only a library to access SQLite functionality through the java JDBC interface. Since we pre-compile the binaries, that means the only thing we control in this case is the version of JDBC included in this library. 

Please visit [sqlite.org](https://www.sqlite.org) if you wish more info on the actual 3.32.3. update.

**Comment by g00229729** [comment]
Many Thanks for fast response!

**Comment by g00229729** [comment]
Thanks for fast response,I will download sqlite 3.32.3 as soon as possible to determine whether the security vulnerability has been fixed.

**Comment by g00229729** [comment]
I will download sqlite 3.32.3 as soon as possible to verify that the security vulnerability has been fixed.
