### ISSUE TITLE
git migration

### ISSUE THREAD

**Issue by javabeanz** [xerial/sqlite-jdbc#581]
Receiving objects: 100% (10516/10516), 216.50 MiB | 1.50 MiB/s, done.
please move to git.

**Comment by bturner** [comment]
Do you mean Git LFS? In order to be hosted on github.com this project already is Git...

**Comment by javabeanz** [comment]
i thought i was checking out an svn project but this is already a git project. ii understand the negative feedback.

the repo could perhaps benefit from compacting with "git gc --aggressive --prune=now"
a giit repo of over 200MB is huge. This link was hulpful https://stackoverflow.com/questions/35410336/how-to-compact-local-git-repo

**Comment by gotson** [comment]
Closing this, please comment if still an issue.

**Comment by bturner** [comment]
> a giit repo of over 200MB is huge

200MB is pretty trivial for Git, actually (but as someone who worked professionally on a Git hosting service I probably have a different view). Since this repository has committed binaries, in the form of sqlite libraries, without switching to something like Git LFS it's going to be hard to keep this really small.

For your own benefit, if you don't need all the history, you could switch from a full clone to a shallow or partial clone (if you're not building) and cut down how much data you need to transfer.

With regards to `git gc --aggressive`, running that locally will do nothing for the size of the repository on the server, which is what controls how large a full clone is from the server, and there's no way to push the results of `git gc` to the server (without deleting the repository and starting over). It would require someone on the Github side doing it on the server-side repository for it to show any benefit. Given the shape of the contents for this repository, it's unlikely a forced repack (which is the useful component of `git gc --aggressive` in this context) would accomplish much. (Additionally, I'd wager Github has automated maintenance that's periodically doing a lot of those things anyway.)
