### ISSUE TITLE
ARMv6: no native library found

### ISSUE THREAD

**Issue by gotson** [xerial/sqlite-jdbc#583]
There is no `armv6` folder in https://github.com/xerial/sqlite-jdbc/tree/master/src/main/resources/org/sqlite/native/Linux

However, the code [can return](https://github.com/xerial/sqlite-jdbc/blob/a497c72922b043b6295a753fe44239eb91da3541/src/main/java/org/sqlite/util/OSInfo.java#L177) `armv6` as an arch type.

It seems armv6 has been disabled, according to [this makefile comment](https://github.com/xerial/sqlite-jdbc/blob/21055a2b75b70039bd9f688deea2408d7d1c2114/Makefile#L106).

Given armv6 is backward compatible with armv5, could we copy the content of https://github.com/xerial/sqlite-jdbc/tree/master/src/main/resources/org/sqlite/native/Linux/arm to an armv6 folder in the meantime?

**Comment by gotson** [comment]
Sadly this doesn't work :(

**Comment by almdudler777** [comment]
hi,

you could try to download the oracle jdk for armhf from their webpage given you register an account. For private use this should still be freely available... my file is named: jdk-8u212-linux-arm32-vfp-hflt.tar.gz, downloaded it ages ago when i did not need an account....

then extract that to some folder and i usually run something along these lines:

```
#!/bin/bash
git clone https://github.com/xerial/sqlite-jdbc.git build/
cd build/ && git fetch --all --tags --prune
git checkout tags/3.21.0.1 # optional only if you want specific release..

find src/main/resources/org/sqlite/native/ -type f -delete

export CCFLAGS="-mfloat-abi=hard"
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf  #where ever you extracted your downloaded jdk

make jni-header clean-native native OS_NAME=Linux OS_ARCH=armv6
mvn -Dmaven.test.skip=true package
```

You might need other dependencies. I run sqlite-jdbc on a raspberry pi zero w with the official raspbian distro... 
`apt install build-essential` should suffice.

After that you should have a custom build ready to go. Beware though i had some problems when i compile my corresponding java application with a different jdk :( (https://github.com/xerial/sqlite-jdbc/issues/371)
If you cant get the oracle jdk you can try the Zulu JDK which should run on armv6 aswell: https://www.azul.com/downloads/zulu-community/?package=jdk

hope this helps.

PS: I think the builld of armv6 binaries was disabled because the docker build system stopped working. But building it yourself is straight forward :)

**Comment by gotson** [comment]
Thanks but I don't have armv6 hardware, but the open source software I develop is used by many people on various hardware.

I need either cross compilation, or someone who could build the library so I could bundle it in my fork (since this project don't accept PRs on compiled libraries without dockcross).
