### ISSUE TITLE
Batch insert does not fill generated IDs.

### ISSUE THREAD

**Issue by xuhao199224** [xerial/sqlite-jdbc#613]
Hey guys, 
I was trying to insert data into sqlite with sqlite-jdbc.
In my situation, I need to insert multiple rows once, then get ids of inserted rows.
I'm using mybatis in my implementation, here is my xml configuration.

<img width="544" alt="截屏2021-06-17 下午4 14 11" src="https://user-images.githubusercontent.com/2443665/122358367-27312980-cf87-11eb-836a-780cc103575d.png">

When I insert a single row with code below, I find id field is right.
`serviceMapper.insert(serviceModel);`
`Long componentFid = serviceModel.getId();` 
Here I get componentFid right.

But when I use batch insert(usually 3 rows once, here is the question),
`componentMapper.insertBatch(componentList);`
`componentList.get(0).getId()` returns the latest id (which should belong to componentList.get(2)), while 
`componentList.get(1).getId()`  and `componentList.get(2).getId()`  returns null.

I downloaded sqlite-jdbc source code and made several breakpoints.
Breakpoints led me to getGeneratedKeys method, and I found `select last_insert_rowid()` was executed.
`select last_insert_rowid()` seems only returns one row, so I can only get one id in my batch insert, bringing the result above.
 
Am I using sqlite-jdbc or mybatis in a wrong way?

**Comment by gotson** [comment]
I don't think `last_insert_rowid` can return more than one ID, so when inserting in batch you may only retrieve the last ID inserted. You can probably verify this assumption with plain SQL using the SQLite command line instead of MyBatis.

You could try to use [RETURNING](https://www.sqlite.org/lang_returning.html) instead, which can "return one result row for each database row that is deleted, inserted, or updated".
