### ISSUE TITLE
SQLite 3.37.0

### ISSUE THREAD

**Issue by dkfellows** [xerial/sqlite-jdbc#694]
[SQLite 3.37.0](https://www.sqlite.org/releaselog/3_37_0.html) was released on 2021-11-27. What's the plan for an update to support it?

**Comment by xerial** [comment]
Hi. Right now, I'm on parental leave. If 3.37.0 can be compiled at ease, it would be around the beginning of 2022

**Comment by Roenbaeck** [comment]
Thank you for the reply. Please note that 3.37.0 has a new feature for strictly typing columns (https://www.sqlite.org/stricttables.html). The `STRICT` keyword now supported in the `CREATE TABLE` statement breaks the current, and likely previous, drivers. See https://github.com/dbeaver/dbeaver/issues/14844 for more information.

**Comment by robd** [comment]
Related PR - https://github.com/xerial/sqlite-jdbc/pull/710

**Comment by jayesh-bhoot** [comment]
Until the PR is merged and a new version is released, here are the steps I followed to build a jar using @pyckle 's fork.

Note: My usecase was to build a jar in order to make DataGrip accept the SQLite 3.37 syntax (`strict` keyword mainly). I still could not make the squiggly syntax errors go away, presumably because the syntax engine does not depend on the driver, but I was able to execute the statements. The outlined steps may go out of date over time. 

1. Clone git@github.com:pyckle/sqlite-jdbc.git
1. Checkout the `upgrade_to_337` branch
1. Ensure that jdk and maven are installed. In my case, I used jdk11 because macOS's pre-installed `java` kept hanging.
1. Ensure docker daemon is installed and running. The build process uses docker.
1. If it doesn't already exist, `export JAVA_HOME=<path>`, where `<path>` is `${which java} minus /bin/java`
1. Run the `package` directive defined in `Makefile`: `make -f Makefile package`
1. The above command should build a `target/sqlite*.jar` file.

**Comment by tjlee** [comment]
> Note: My usecase was to build a jar in order to make DataGrip accept the SQLite 3.37 syntax (`strict` keyword mainly). I still could not make the squiggly syntax errors go away, presumably because the syntax engine does not depend on the driver, but I was able to execute the statements. The outlined steps may go out of date over time.

DataGrip syntax highlighting engine doesn't depends on driver versions. If you've got syntax issues, could you report them in [DataGrip bug tracker](https://youtrack.jetbrains.com/newIssue?project=DBE)?

**Comment by jayesh-bhoot** [comment]
> > Note: My usecase was to build a jar in order to make DataGrip accept the SQLite 3.37 syntax (`strict` keyword mainly). I still could not make the squiggly syntax errors go away, presumably because the syntax engine does not depend on the driver, but I was able to execute the statements. The outlined steps may go out of date over time.
> 
> DataGrip syntax highlighting engine doesn't depends on driver versions. If you've got syntax issues, could you report them in [DataGrip bug tracker](https://youtrack.jetbrains.com/newIssue?project=DBE)?

Yes. I have [already logged that issue](https://youtrack.jetbrains.com/issue/DBE-15140) on their tracker. They have already marked it as Fixed (still unreleased, may be).

**Comment by fire** [comment]
Can we schedule the work or maybe try merging existing work to make a release?

**Comment by gotson** [comment]
We will most likely try to release version 3.39 soon
