### ISSUE TITLE
JVM crash due to  pthread_mutex_lock+0x0

### ISSUE THREAD

**Issue by wenger66** [xerial/sqlite-jdbc#719]

**Comment by wenger66** [comment]
[hs_err_pid19083.log](https://github.com/xerial/sqlite-jdbc/files/8029042/hs_err_pid19083.log)
[hs_err_pid31344.log](https://github.com/xerial/sqlite-jdbc/files/8029043/hs_err_pid31344.log)

The JVM crashed two times. Attached the crash file with all details.

1
Stack: [0x00002b3f86097000,0x00002b3f86198000],  sp=0x00002b3f861962d8,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpthread.so.0+0x93a0]  pthread_mutex_lock+0x0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J  org.sqlite.core.NativeDB.step(J)I
.....


2
Stack: [0x00002ad8c78a2000,0x00002ad8c79a3000],  sp=0x00002ad8c79a16f8,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpthread.so.0+0x8dd0]  pthread_mutex_lock+0x0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J  org.sqlite.core.NativeDB.reset(J)I

**Comment by gotson** [comment]
Please use the issue templates

**Comment by pyckle** [comment]
This looks like the use after free bug which I fixed in this pr: https://github.com/xerial/sqlite-jdbc/pull/685

Most likely you are using a Connection in two (or more threads), and one is calling close while the other thread is running a query. Consider fixing your code not to do this (having one thread close a connection while another is running a query isn't great application behavior), or make a build from my PR branch so it throws an exception rather than causes a JVM crash.

**Comment by gotson** [comment]
Should be closed by #685, released as part of `3.39.2.0`. I will be closing this, please comment if the problem happens again on `3.39.2.0`.
