### ISSUE TITLE
how to disable transactions

### ISSUE THREAD

**Issue by andykais** [xerial/sqlite-jdbc#726]
it seems like every database call is wrapped in a transaction. The options I appear to have are either implicit or explicit transactions, but no option for simple atomic sql commands.

### Option 1:
```java
SQLiteConnection conn = (SQLiteConnection) DriverManager.getConnection("jdbc:sqlite:".concat(databaseFile));
conn.setBusyTimeout(5000);
conn.setAutoCommit(true);

PreparedStatement stmt = conn.prepareStatement("DELETE FROM events WHERE id = ?");
stmt.setInt(1, 10);
// sqlite-jdbc wraps this statement in `begin;`, `commit;` calls
stmt.executeUpdate();
stmt.close();
```

### Option 2:
```java
SQLiteConnection conn = (SQLiteConnection) DriverManager.getConnection("jdbc:sqlite:".concat(databaseFile));
conn.setBusyTimeout(5000);
conn.setAutoCommit(false); // sqlite-jdbc calls `begin;` here

PreparedStatement stmt = conn.prepareStatement("DELETE FROM events WHERE id = ?");
stmt.setInt(1, 10);
stmt.executeUpdate();
stmt.close();
conn.commit(); // my changes are not committed until this is called.
```

Is it possible to write to a sqlite database without transactions? I am seeing lots of `SQLITE_BUSY` errors cropping up in my application that has inserts from another process. I believe unless I am misunderstanding something fundamental about sqlite, I can increase speeds and avoid some of the busy errors I see by removing transactions. My database is in WAL mode.

**Comment by gotson** [comment]
From the [SQLite documentation](https://www.sqlite.org/lang_transaction.html#:~:text=No%20reads%20or%20writes%20occur%20except%20within%20a%20transaction.):

> No reads or writes occur except within a transaction.

The driver will always start a transaction, so all transactions will be explicit transactions, instead of implicit transactions.



> I am seeing lots of `SQLITE_BUSY` errors cropping up in my application that has inserts from another process. I believe unless I am misunderstanding something fundamental about sqlite, I can increase speeds and avoid some of the busy errors I see by removing transactions. My database is in WAL mode.

You're touching a point that is not directly related to this driver, but more generic to SQLite. There are some good resources you can find about it, like [this](https://activesphere.com/blog/2018/12/24/understanding-sqlite-busy).

**Comment by andykais** [comment]
Thank you for the clarification
